# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/134waAzjGNwfGr0-AmDnIcjjzdTjo_kSQ
"""

import streamlit as st
import pandas as pd
import pickle

# Load model
model = pickle.load(open("model.pkl", "rb"))

st.set_page_config(page_title="Crop Recommendation", layout="centered")

st.title("🌾 Smart Crop Recommendation System")
st.markdown("Enter soil and environmental details to get the best crop suggestion")

# Input sliders (better than typing)
N = st.slider("Nitrogen (N)", 0, 150, 50)
P = st.slider("Phosphorus (P)", 0, 150, 50)
K = st.slider("Potassium (K)", 0, 150, 50)
temperature = st.slider("Temperature (°C)", 0, 50, 25)
humidity = st.slider("Humidity (%)", 0, 100, 50)
ph = st.slider("pH Value", 0.0, 14.0, 6.5)
rainfall = st.slider("Rainfall (mm)", 0, 300, 100)

if st.button("🌱 Predict Crop"):
    data = pd.DataFrame({
        'N': [N],
        'P': [P],
        'K': [K],
        'temperature': [temperature],
        'humidity': [humidity],
        'ph': [ph],
        'rainfall': [rainfall]
    })

    prediction = model.predict(data)

    st.success(f"✅ Recommended Crop: {prediction[0]}")